### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by engine303** [romovpa/bigartm-docker#1]
Hello! Can you create docker image of last version of bigartm, please?
best regards, Dmitry

**Comment by sashafrey** [comment]
@ParpulovDmitry Hi Dmitry,
Right now I don't have capacity to maintain up-to-date docker image, sorry.... The question about docker container for BigARTM was included in our survey (https://github.com/bigartm/bigartm/issues/460), and based on the feedback we decided to focus on `pip install bigartm` (which isn't ready yet, but we are in progress).

Is there any reason why building the BigARTM from sources is difficult in your case? My impression was that on Linux and MAC it goes fairly smoothly. I'd be happy to help with that, if you have build issues, etc..

If you absolutely require Docker, maybe @romovpa or @JeanPaulShapo  can help on this?

**Comment by ofrei** [comment]
@ParpulovDmitry Sorry, this was slow but now BitARTM docker image is now upgraded to the latest version, v0.8.2. From  now on the plan is to keep it in sync. 

NB: the image was moved to another repo, so now please use `ofrei/bigartm` instead of `romovpa/bigartm`. Like this:
```
docker pull ofrei/bigartm
docker run -t -i ofrei/bigartm bigartm
```
