### ISSUE TITLE
How to Run BigARTM Docker image with passing input files.

### ISSUE THREAD

**Issue by najeerahmmadsk** [romovpa/bigartm-docker#2]
How to Run BigARTM Docker image with passing input files.

**Comment by ofrei** [comment]
Basically you need `docker cp` command, as described [here](http://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container).

Or, with more context, it works like this:
* `docker pull ofrei/bigartm` to fetch latest docker image for bigartm
* `docker run -t -i ofrei/bigartm` to run docker container with bigartm
* [Detach](http://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process) froom docker container with `Ctrl+P`, `Ctrl+Q` shortcut
* Run `docker ps` to find the ``CONTAINER ID`` of your container.
```
CONTAINER ID        IMAGE               COMMAND             CREATED            
c3a994adb4fe        ofrei/bigartm       "/bin/bash"         10 minutes ago      
```
* Run `docker cp` to [copy files from host to docker container](http://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container)
* [attach](https://docs.docker.com/engine/reference/commandline/attach/) to docker container with `docker attach <container_id>`
